### ISSUE TITLE
how install this module in qgis?

### ISSUE THREAD

**Issue by dfguerrerom** [SMByC/StackComposed-Qgis-processing#1]
I've trying to find documentation on how to install this plugin on qgis but haven't found anything so far, it's already available?

**Comment by XavierCLL** [comment]
Hi Dani, how is it going?

I have some plugins that at the moment are not in the official Qgis plugin repository, I have them here:

https://drive.google.com/drive/folders/10FVZ_eRfHmyu1vIrF2279BBjZy6q-dJX
